Parameters:
  SourceVPCId:
    Description: Select the source VPC-ID
    Type: AWS::EC2::VPC::Id
  SourceVPCCIDRRange:
    Description: The CIDR Range of Source VPC
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  PeerVPC:
    Description: The Peer VPC-ID
    Type: String
  PeerVPCRegion:
    Description: The Peer VPC Region
    Type: String
    AllowedValues:
      - us-east-1
      - us-west-2
  PeerVPCCIDRRange:
    Description: The CIDR Range of Source VPC
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  PeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties: 
      PeerRegion: !Ref PeerVPCRegion
      PeerVpcId: !Ref PeerVPC
      VpcId: !Ref SourceVPCId
  SourcePeeringRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SourceVPCId
  PeeringRouteSource:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref PeerVPCCIDRRange
      RouteTableId: !Ref SourcePeeringRT
      VpcPeeringConnectionId: !Ref PeeringConnection
  PeerPeeringRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PeerVPC
  PeeringRoutePeer:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref SourceVPCCIDRRange
      RouteTableId: !Ref PeerPeeringRT
      VpcPeeringConnectionId: !Ref PeeringConnection