AWSTemplateFormatVersion: 2010-09-09
Resources:
  rdsudacityaws:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: '20'
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade: 'true'
      DBInstanceClass: db.t2.micro
      Port: '3306'
      StorageType: gp2
      BackupRetentionPeriod: '7'
      MasterUsername: udacityaws
      MasterUserPassword: MyPassword
      PreferredBackupWindow: '04:04-04:34'
      PreferredMaintenanceWindow: 'tue:06:15-tue:06:45'
      DBName: MyDatabase
      Engine: mysql
      EngineVersion: 8.0.17
      LicenseModel: general-public-license
      DBSubnetGroupName: !Ref dbsubnetrdstestpri
      VPCSecurityGroups:
        - !Ref sgUDARRDatabase
  dbsubnetrdstestpri:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: rds-test-pri
      SubnetIds:
        - subnet-0129daa695433958e
        - subnet-0d7142bead2da6722
  sgUDARRDatabase:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Udacity ARR Project - Database Security Group
      VpcId: vpc-02d583a92c7272a8b
      Tags:
        - Key: Name
          Value: UDARR-Database
  ingress1:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref sgUDARRDatabase
      IpProtocol: tcp
      FromPort: '3306'
      ToPort: '3306'
      SourceSecurityGroupId: sg-06503ddba67d87312
      SourceSecurityGroupOwnerId: '506189848464'
  egress1:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      GroupId: !Ref sgUDARRDatabase
      IpProtocol: '-1'
      CidrIp: 0.0.0.0/0
Description: RDS

rdsudacityawsrr:
  Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: '20'
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade: 'true'
      DBInstanceClass: db.t2.micro
      StorageType: gp2
      BackupRetentionPeriod: '0'
      MasterUsername: udacityaws
      MasterUserPassword: MyPassword
      PreferredBackupWindow: '04:04-04:34'
      PreferredMaintenanceWindow: 'tue:06:15-tue:06:45'
      SourceDBInstanceIdentifier: 'arn:aws:rds:us-east-1:506189848464:db:udacityaws'
      VPCSecurityGroups:
        - sg-09b1c247f45b8564d
Description: rdsrr
