AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SubnetIds:
    Description: A name that is prefixed to resource names
    Type: List<AWS::EC2::Subnet::Id>
  DBSubnetGroupName:
    Description: The Name of the DB Subnet Group
    Type: String
  DBSubnetGroupDescription:
    Description: The Name of the DB Subnet Group
    Type: String  
Resources:
  RDSSubNetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: !Ref DBSubnetGroupDescription
      DBSubnetGroupName: !Ref DBSubnetGroupName
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: "CourseWork"
          Value: "udc"
