Parameters:
  EC2InstanceName:
    Description: The Name of the instance
    Type: String
  EC2KeyPair:
    Description: Amazon EC2 Key Pair
    Type: AWS::EC2::KeyPair::KeyName
  SubnetId:
    Description: Enter the Subnets
    Type: AWS::EC2::Subnet::Id
  SecurityGroupId:
    Description: Enter the Subnets
    Type: AWS::EC2::SecurityGroup::Id
  InstanceClass:
    Description: The instance class of the RDS instance
    Type: String
    Default: "t2.micro"
    AllowedValues:
      - "t2.micro"
      - "t2.small"
      - "t2.medium"
      - "t3.micro"
      - "t3.small"
      - "t3.medium"
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c94855ba95c71c99
    us-west-2:
      AMI: ami-0841edc20334f9287
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Init:
        config: 
          packages: 
            yum:
              mysql: []
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EC2InstanceName
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI
      InstanceType: !Ref InstanceClass
      KeyName: !Ref EC2KeyPair
      Monitoring: true
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId 
      UserData:
        'Fn::Base64': 
          !Sub |
            #!/bin/bash -xe            
            # Ensure AWS CFN Bootstrap is the latest
            yum install -y aws-cfn-bootstrap
            # Install the files and packages from the metadata
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance  --region ${AWS::Region}
  
