Parameters:
  SourceVPC:
    Description: Select the source VPC
    Type: AWS::EC2::VPC::Id
  SourceVPCCIDRRange:
    Description: The CIDR Range of Source VPC
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  PeerVPC:
    Description: The Peer VPC-ID
    Type: String
  PeerVPCRegion:
    Description: The Peer VPC Region
    Type: String
    AllowedValues:
      - 'us-east-1'
      - 'us-west-2'
  PeerVPCCIDRRange:
    Description: The CIDR Range of Source VPC
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  PeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties: 
      PeerRegion: !Ref PeerVPCRegion
      PeerVpcId: !Ref PeerVPC
      VpcId: !Ref SourceVPC